resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: source
  type: git
  check_every: 24h
  source:
    uri: https://github.com/jonm/s3pypi

- name: pr
  type: pull-request
  check_every: 24h
  source:
    repository: jonm/s3pypi
    access_token: ((github-access-token))
    
- name: concourse-terraform
  type: git
  source:
    uri: https://github.com/Snapkitchen/concourse-terraform

- name: concourse-terraform-image
  type: docker-image
  source:
    repository: snapkitchen/concourse-terraform
    tag: '0.11.14'
    
jobs:
- name: build-pr
  plan:
  - get: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: pr
      status: PENDING
  - get: concourse-terraform
  - task: terraform-plan
    file: pr/ci/task_tf_plan.yml
    input_mapping: { terraform-source-dir: pr }
    params:
      ERROR_ON_NO_CHANGES: false
      TF_BACKEND_TYPE: s3
      TF_BACKEND_CONFIG_bucket: ((tf-bucket))
      TF_BACKEND_CONFIG_key: s3pypi.tfstate
      TF_BACKEND_CONFIG_region: ((tf-region))
      TF_BACKEND_CONFIG_access_key: ((aws-access-key-id))
      TF_BACKEND_CONFIG_secret_key: ((aws-secret-access-key))
      TF_VAR_aws_access_key: ((aws-access-key-id))
      TF_VAR_aws_secret_key: ((aws-secret-access-key))
    on_failure:
      put: pr
      params:
        path: pr
        status: FAILURE
  - put: pr
    params:
      path: pr
      status: SUCCESS
      comment_file: tfplan/plan.md

- name: build
  plan:
  - get: source
    trigger: true
  - get: concourse-terraform
  - task: terraform-apply
    file: source/ci/task_tf_apply.yml
    params:
      ERROR_ON_NO_CHANGES: false
      TF_BACKEND_TYPE: s3
      TF_BACKEND_CONFIG_bucket: ((tf-bucket))
      TF_BACKEND_CONFIG_key: s3pypi.tfstate
      TF_BACKEND_CONFIG_region: ((tf-region))
      TF_BACKEND_CONFIG_access_key: ((aws-access-key-id))
      TF_BACKEND_CONFIG_secret_key: ((aws-secret-access-key))
      TF_VAR_aws_access_key: ((aws-access-key-id))
      TF_VAR_aws_secret_key: ((aws-secret-access-key))
